name: Build Desktop App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-desktop:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        python-version: [3.10]  # Changed from 3.11 to avoid pywin32 issues

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ----------------- FRONTEND SETUP ------------------

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: eCyber/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./eCyber
        run: npm ci

      - name: Build React frontend
        working-directory: ./eCyber
        run: npm run build

      # ----------------- BACKEND SETUP -------------------

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Skip pywin32 on non-Windows OS
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pip install pywin32==310
          fi
          pip install pyinstaller

      - name: Build backend binary with PyInstaller
        working-directory: ./backend
        run: |
          pyinstaller ecyber_backend.spec
          mkdir -p ../eCyber/electron/backend/_internal
          cp -r dist/ecyber_backend_dist/* ../eCyber/electron/backend/_internal/

      # ----------------- ELECTRON BUILD -------------------

      - name: Package Electron application
        working-directory: ./eCyber
        run: npm run package

      # ----------------- UPLOAD BUILDS -------------------

      - name: Upload packaged application
        uses: actions/upload-artifact@v4
        with:
          name: eCyber-${{ runner.os }}-Node${{ matrix.node-version }}
          path: ./eCyber/dist_electron/
