name: Build Desktop App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-desktop:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20.x]
        python-version: ["3.11.9"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ----------------- FRONTEND SETUP ------------------

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: eCyber/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./eCyber
        run: npm ci

      - name: Build React frontend
        working-directory: ./eCyber
        run: npm run build

      # ----------------- BACKEND SETUP -------------------

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          # Install pywin32 only on Windows
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            pip install -r requirements.txt
          else
            # On Linux/Mac, skip pywin32 by filtering requirements file dynamically
            grep -vE "pywin32|pywin32-ctypes" requirements.txt > reqs_no_win.txt
            pip install -r reqs_no_win.txt
          fi
          pip install pyinstaller
        shell: bash

      - name: Build backend binary with PyInstaller
        working-directory: ./backend
        run: |
          pyinstaller ecyber_backend.spec
          mkdir -p ../eCyber/electron/backend/_internal
          cp -r dist/ecyber_backend_dist/* ../eCyber/electron/backend/_internal/
        shell: bash

      # ----------------- ELECTRON BUILD -------------------

      - name: Package Electron application
        working-directory: ./eCyber
        run: npm run package

      # ----------------- UPLOAD BUILDS -------------------

      - name: Upload packaged application
        uses: actions/upload-artifact@v4
        with:
          name: eCyber-${{ matrix.os }}-Node${{ matrix.node-version }}
          path: ./eCyber/dist_electron/
